apiVersion: v1
kind: Namespace
metadata:
  name: air-tek

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: air-tek
spec:
  selector:
    matchLabels:
      app: infraapi
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: infraapi
        tier: backend
    spec:
      containers:
        - name: infraapi
          image: {{ .Values.infraapi.image }}
          ports:
            - name: tcp
              containerPort: 5000
          resources:
            requests: #Requests describes the minimum amount of compute resources required
              memory: "100Mi"
              cpu: "100m"
            limits: #Limits describes the maximum amount of compute resources allowed
              memory: "150Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: infraapi
  namespace: air-tek
spec:
  selector:
    app: infraapi
    tier: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: air-tek
spec:
  maxReplicas: 10
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  targetCPUUtilizationPercentage: 80
